// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, created_at, updated_at, title, url, feed_id, published_at, description)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, created_at, updated_at, title, url, description, published_at, feed_id
`

type CreatePostParams struct {
	ID          uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Title       string
	Url         string
	FeedID      uuid.UUID
	PublishedAt sql.NullTime
	Description sql.NullString
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Url,
		arg.FeedID,
		arg.PublishedAt,
		arg.Description,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}

const fetchUserPosts = `-- name: FetchUserPosts :many
SELECT posts.title, posts.url FROM posts
JOIN feed_follow ON posts.feed_id = feed_follow.feed_id
WHERE feed_follow.user_id = $1
`

type FetchUserPostsRow struct {
	Title string
	Url   string
}

func (q *Queries) FetchUserPosts(ctx context.Context, userID uuid.UUID) ([]FetchUserPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchUserPosts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchUserPostsRow
	for rows.Next() {
		var i FetchUserPostsRow
		if err := rows.Scan(&i.Title, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
